### ISSUE TITLE
Race condition: 2 workers poll the same job

### ISSUE THREAD

**Issue by rtannenbaum** [google/data-portability#98]
API:
2018-01-26 20:49:36,196 [http-server-16] INFO  org.dataportabilityproject.job.PortabilityJobFactory - Creating new PortabilityJob, id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e

Worker 1:

2018-01-26 20:50:12,244 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled pollForUnassignedJob, found id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
2018-01-26 20:50:12,943 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Completed updateJobStateToAssignedWithoutAuthData, publicKey: 162

2018-01-26 20:50:33,051 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled lookupAssignedWithAuthDataJob, found auth data, id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
2018-01-26 20:50:33,056 [main] DEBUG org.dataportabilityproject.worker.WorkerImpl - Begin processing jobId: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
Jan 26, 2018 8:50:33 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SEVERE: Caught an exception in Thread[main,5,main].  Shutting down.
java.lang.RuntimeException: Failed to invoke public org.dataportabilityproject.shared.auth.AuthData() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at org.dataportabilityproject.worker.WorkerImpl.deSerialize(WorkerImpl.java:108)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:92)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:69)
	at org.dataportabilityproject.worker.WorkerMain.main(WorkerMain.java:31)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104)

Worker 2:

2018-01-26 20:50:12,382 [JobPollingService RUNNING] DEBUG org.dataportabilityproject.worker.JobPollingService - Polled pollForUnassignedJob, found id: ed03f0ba-0b8c-4d55-bce0-70c9c747f35e
Jan 26, 2018 8:50:12 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SEVERE: Caught an exception in Thread[main,5,main].  Shutting down.
java.lang.IllegalStateException: Expected the service JobPollingService [FAILED] to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:293)
	at com.google.common.util.concurrent.AbstractScheduledService.awaitTerminated(AbstractScheduledService.java:434)
	at org.dataportabilityproject.worker.WorkerImpl.pollForJob(WorkerImpl.java:75)
	at org.dataportabilityproject.worker.WorkerImpl.processJob(WorkerImpl.java:60)
	at org.dataportabilityproject.worker.WorkerMain.main(WorkerMain.java:31)
Caused by: java.lang.IllegalArgumentException: Job not found
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.dataportabilityproject.job.JobDao.updateJobState(JobDao.java:224)
	at org.dataportabilityproject.job.JobDao.updateJobStateToAssignedWithoutAuthData(JobDao.java:173)
	at org.dataportabilityproject.worker.JobPollingService.pollForUnassignedJob(JobPollingService.java:83)
	at org.dataportabilityproject.worker.JobPollingService.runOneIteration(JobPollingService.java:57)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:188)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rtannenbaum** [comment]
blocks #88
